version : '3.1'

services:

  ebpf:
    image: ebpf-dev
    cap_add:
      - SYS_PTRACE
    build:
      context: .
      dockerfile: Dockerfile.ebpf
    volumes:
      - ./:/workspaces/learning-vscode-containers
